### ISSUE TITLE
Request: Live lateness and ETA sort

### ISSUE THREAD

**Issue by DazrahT** [LinqToException/VirTracks#10]
Would it be possible to rather than show overdue trains (where it will show on time and then start counting the delay up from the booked ETA) to instead have an option that will track the delay inbound and update this figure as an ETA time and if possible then have an option to the automatically resort the EDR list to slot the train down the list into where it is expected to arrive.

Perhaps have an option that allows you to toggle it so it will only auto-sort for late trains only but anything early will not auto-sort unless you tell it to.

**Comment by LinqToException** [comment]
Different sorting options is definitely something I could imagine to do. I've noticed that it can get pretty annoying if you have 1-2 very late trains, and about 10-20 in-between (although the recent introduction of the time scope helps a lot, it's not suitable for all stations, e.g. those with long blocks like Psary and super early trains like the 629xxx, which can show up with -50').

The problem with the "live lateness" is the determination of said lateness. What I could easily do (and was thinking about) was to add the "last arrival/departure indicator", where you would see the difference on the last station. For example, when a train leaves Psary with +30', it would display +30' already, even if you're in, say, Katowice. However, this ignores that trains can (and have) some "buffer" between stations, and as such, can make up lost time. The further away you are, the less precise this value would be (as each stop can likely add/subtract some time).

In theory, I should have the data by now to know how long a train, on average/most of the time, takes to get from A to B, and therefore could say "To get from the last station is was seen at to you, it has to pass these stations, and likely takes this long to do so". However, this data is a bit fragile, because it's based on a "majority vote" (e.g. if the Warsaw AI acts up again and delays all trains, it would think that it takes _longer_ for that part).

So in the end, I would say this is two things:

1. Add the option to tweak the sorting (default as it is now, missing/departed then arrived then others, and then as an additional modifier whether to use the scheduled time like now or the "real time").
2. Add the option to display a more "recent ETA", rather than the ETA to the current time/scheduled departure.

The only question is what, or how, this real time should be calculated. I'm not a big fan of estimation in general, as I feel like it becomes wildly inaccurate, especially over longer distances. I would also like to avoid trying to mess with distances, velocities and that kind of thing, as VirTracks is not doing anything like that right now. I could definitely imagine something like "Last departure at station X [+5']" though.

In general, one of the updates I was thinking about what to add was the complete customization of the table. Basically, I would offer you a list of columns, and you could then decide which columns you want to see, and where to see them - allowing you to customize your station view completely to your liking. I think this would end up as another one or two columns for that, similar to how e.g. the signals are their own today.

**Comment by DazrahT** [comment]
So for "live lateness" I was thinking use whatever lateness it used passing its last reporting location, rather than an actual updating as it moves lateness, so therefore at least it slots it sort of into the right place on the table. This is probably lower down the list than the other issue I opened which would be more of a help rather than having to keep hoving over the train ID to get its lateness (as at present)

So something like "B XX:XX +15" or use its full name and "Bedzin XX:XX 15 LATE" as an example

**Comment by LinqToException** [comment]
Ah, I think I understand now. So basically, both issues deal with the concept of "last known lateness". This one is for sorting, the other one is for displaying in the table, correct? There's a bit of an overlap here.

I think both these things - sort options and another column - would be rather easy to add, given the framework that I have. It's just a question of whether I add it as another configuration toggle, or wait for the customizable-columns update.

**Comment by DazrahT** [comment]
"This one is for sorting, the other one is for displaying in the table, correct? There's a bit of an overlap here." 

Yes, sorry, I should have made it a little clearer 👍

**Comment by LinqToException** [comment]
No worries, we got there in the end! I'll let you know once I've made the changes and published them.

**Comment by LinqToException** [comment]
2.4.0 has been pushed to prod which adds two new features:

1. Sort mode for the station view - currently you can pick between the old default (timetable arrival ascending), and the new variant which includes the known delay.
2. I thought it might be useful, but I have mixed feelings - the option to sort the trains by state (missed/departed trains first, then all arrived trains, then all others). I've had marked trains separate as well, but then it became quickly confusing as to which train was now going where and how to prioritize them, so I've stuck with the arrival-not-arrival rule... for now. I find it confusing and as such, it's something that might be going away in the future. Perhaps it'll grow on me. Not sure.

**Comment by DazrahT** [comment]
I'll have a play around with it either today or tomorrow and give some feedback if it requires it, but thank you for taking the issues/enhancements on board!
