### ISSUE TITLE
Actual speed missing

### ISSUE THREAD

**Issue by RWagener** [LinqToException/VirTracks#11]
It would be a good idea to have also the actual speed displayed on the station EDR screen, as a new column to choose from. We already have the VMax speed interesting too.

It's important to have this information that we actually could see when we are in the disptacher box, but that we don't have when we are in the computer screen (or the EDR screen) of the dispatcher box.

**Comment by LinqToException** [comment]
I'm partial to this feature, because it feels a bit cheaty from a dispatcher point of view (currently, except for the map, VirTrack's data is what you could reliably fetch from a modern dispatching system, I think), and it would also increase VirTrack's traffic by a lot because you're now receiving velocity updates for all trains on the map all the time.

What would you realistically use the velocity for? Like, how does it help you to dispatch? I personally feel that it just feels a bit "wrong". I hate it when Bedzin, a relais box, asks me why I am "only driving 37 km/h". There's no way (that I can think of) you would know that in real life; and it makes dispatching a bit... more vague.

But I'm open for discussions on this front.

**Comment by RWagener** [comment]
OK. I understand that.

For me, it's to have a better view of trains approaching and these which are stopped in the entry signal of my box, especially when there is a queue of trains waiting to enter (we can have more than one train in a block, because they can pass the red signal at 20 km/h). Also, but not as important, it's to verify the departing trains they depart really (and don't stay static on the platform). It happends me sometimes that the driver didn't manage the starting of his train, and stay in the platform.

Yes, I know, we already have the signal in front of the train.

No problem, if you can't do that (even if it would be optional). You have achieved a very, very good job. Your EDR is really for me the best one (better than the french one, even if I'm french). I use it on a separate screen (I've two monitors).

I think it's also (nearly) the same thing than having a camera to look at the crossings, platforms, signals, and so on ... (today, they say that it will be implemented).

**Comment by LinqToException** [comment]
Those are some valid points, but I feel like we could find better solutions for this.

As example, here's some ideas that have been floating around in my head for a while, but I have not yet decided whether to implement or not, which feel like they could be related to what you want (in a roundabout way):

- **Track/Line-Precise 'From':** Currently, VirTracks only displays the origin station; not the line (or track). As VirTracks does know the signals and the relations between signals, it would be feasible to announce trains more precise - i.e. "This train is coming from Katowice Track 3", rather than just "KO" once the train is heading towards a signal that can only end up at one entry signal in your station. This would require some configuration on my end to say "This signal represents track X/Line Y".
- **Highlighting with Queues:** Rather than just highlighting a train (like now), highlighted trains could receive a number - the order in which they were highlighted. That way, you could identify which train is expected in what order. You could scope this to the origin track (i.e. in OL, trains from WP and trains from PL would both start at 1 and then count up respectively). Upon arrival, the numbers are all shifted down, i.e. train 2 becomes 1, and so forth. If the precise-from is implemented, this could perhaps be scoped down even more, so you could see which train is expected on what track in what order.
- **Partial Decouplement from Highlights and Signals:** Currently, highlights are caused by a train driving towards a signal. Since the timetable API has been known, VirTracks does know the entire path of a train and as such could do automatic highlights - i.e. if a train departs at PL, it will automatically be marked highlighted in OL or OP.

I'm mostly concerned about the frequent updates. I've made it a point to make VirTracks somewhat bandwidth efficient and when compared with other EDR/map solutions, or the official EDR, I feel like I'm doing pretty well.

If we are strictly talking about arrival/departure though, what I could offer (and already do in the backend) is a simple "is the train currently stopped?" flag, It's currently used for the alerts and not sent to the frontend, but this could be extended. I'm just wondering if that would be useful. To be honest, you can always switch to the map view (quickly) to see what's going on at your station, as it will be centered around your selected station (although to see if a train moves without clicking on it, you might need to wait 10s or so).

**Comment by LinqToException** [comment]
Forgot that last part: Also, thanks! Feedback means a lot to me. The new Steam Overlay update also makes interesting options possible with having VirTracks pinned to the side of your screen - which may prompt me to make a sort of "mini view" which could be used alternatively for streaming/as an overlay, with a separate column interface. It's something I could think about.

**Comment by LinqToException** [comment]
I've gone for the low hanging fruit and, as a proof of concept, added the train state as a column. It kinda looks like this right now:

**Comment by RWagener** [comment]
I’m sorry. 
i will ne out for one week

**Comment by LinqToException** [comment]
No worries! I'll try to play around a bit and see where it could fit.

**Comment by DazrahT** [comment]
> It's important to have this information that we actually could see when we are in the disptacher box, but that we don't have when we are in the computer screen (or the EDR screen) of the dispatcher box.

We certainly don't have this in real signal boxes, the only way we know how fast a train is going is to ask them directly or to observe the speed when it passes over a Hot Axle Box Detector (HABD) which conveniently tells us how fast a train is going (This is in the UK btw)

Apart from that, we don't know.
