### ISSUE TITLE
Color usage on map

### ISSUE THREAD

**Issue by Tobbzz** [LinqToException/VirTracks#18]
I don't really understand the train color meanings on the map. But would it be possible to use different usages for colors? Like by train type, or destination, or max speed.

I would find it very useful to display how early/late train is running. As a dispatcher you want to know how to prioritize. If a train is late you know that other trains might held longer, or the opposite.
Or maybe a colorized dot on bottom right on every train (like users active status on Facebook Messenger or Microsoft Teams), then two colors can be used for displaying things.

**Comment by LinqToException** [comment]
The map colors are based on train type, actually!

- EIP are red
- EC, EIC, EN are orange
- IC are a lighter orange
- TLK are orange-yellow-y
- RE, IR, RP, RO and REG are yellow-y
- PWJs are cyan-ish
- and all other trains are blue

I don't think destination would be an useful stat to have (because, well, what does count as destination, specifically for trains that have already passed your station?). Max speed might be an interesting one, but might suffer from a weird scale (because we have at least 65/80/100/120/140/200 as possible values).

Delay is a tricky one, because it would need constant updates and/or would only update once a train has passed a station - which works fine in dispatch mode, but I feel wouldn't quite work in the map.

You can click on the trains today already to open a more informative display, including their timetable and current delay, their current velocity (estimation) and their vMax. So some of this information is already available, but not on the map itself for all trains.

**Comment by LinqToException** [comment]
I've added this feature (more or less) in 2.6.0 with three coloring modes at the moment:

- Types (based on the schema mentioned in the previous comment)
- Delays (red-to-green-to-blue for late-to-on-time-to-early)
- VMax (blue-to-red).

I'm not particularly happy with the VMax one, because it's... fickle. From the top of my head, there are at least the following vMax in the game:

- 200
- 160
- 140
- 130
- 120
- 100
- 90
- 80
- 75
- 50

... and possibly more coming with the update. This would require 10 individually mapped colors, in some kind of logical arrangement, to make sense - yet some tiers have major differences (200<->160), while others are super minimal (75<->80). I don't think buckets would help here either, as it would reduce the amount from 10 to maybe 7 or so.

That being said, I'll close this issue for the time being because the requested functionality should be available for testing now. It can always be reopened (or another issue can be created) if something's not working out.
