### ISSUE TITLE
Times are not identical to Gametime

### ISSUE THREAD

**Issue by titanier2002** [LinqToException/VirTracks#19]
Hi, on DE1 (maybe on more server) the ingame time is now UTC+1 (winter time) and the VIR Tracks time is UTC+2 so all trains have 1 hour delay on the board.

**Comment by LinqToException** [comment]
Hi, thanks for your report!

This was probably due to my excessive caching of data (i.e. I'm not automatically re-fetching the data for no reason yet). I've restarted the server and it looks OK now.

I'm keeping this issue open while thinking about a proper way to deal with this issue - likely by having something like an automated 4-in-the-morning-data-refresh.

**Comment by LinqToException** [comment]
Added a daily cronjob in 2.6.0 to re-fetch the current data sometimes in the morning.
