### ISSUE TITLE
Request: Last Reported Location Column (+lateness)

### ISSUE THREAD

**Issue by DazrahT** [LinqToException/VirTracks#9]
Would it be possible to add another column to the EDR where it shows the last reported location, this information is already available when you hover over a train, but I think it'd be good for dispatchers if this information was more easily available along with it's lateness (or earliness) at that location.

**Comment by LinqToException** [comment]
See [this comment](https://github.com/LinqToException/VirTracks/issues/10#issuecomment-1559945304). I've been thinking about adding something like that, and it would definitely be useful.

The latter part of the comment applies much more to this issue than the other one (where the other one is mostly a "what should lateness be?", this one is pretty much defined because as you've said, it's already known).

**Comment by LinqToException** [comment]
I've more or less finished the configurable column bits, so adding this one was pretty straight-forward. 

![image](https://github.com/LinqToException/VirTracks/assets/47725963/e77f7a54-bc2d-48ac-86eb-4ca52ba03450)

There's two things that still need to be figured out:

1. I'm not happy with the presentation. We need to encode three bits of information: The station, the delay, and whether it was an arrival or departure. I think the current one makes sense if you know what it is, but it's not as obvious as I would like. I was thinking of perhaps adding a label (ARR/DEP), but it would need to be color-coded for best readability I think, but I'm not sure what colors would work there.
2. What is "lateness" in regard to arrivals? For example, a train may arrive in OL with -10 and has a layover of 5. It will be displayed as "OL, arrival, -10". However, it cannot depart, and its departure time should have been over five minutes ago - will it still be displayed as "OL, arrival, -10" because that's _technically_ what was last reported/called in, or would it now turn into something like "OL, departure, +5", counting up?

**Comment by DazrahT** [comment]
Glad to see you've made some progress so soon with it!

Regarding No 2 and "lateness", I'm thinking on the lines of how our computer system at work presents delays, in that it will only show whatever the last report was and doesn't take into account of any make up time or standing time, so a train could arrive at station A 20 late and still show 20 late until it reports again as departing, this itself may be an updated delay, early or right time.

**Comment by DazrahT** [comment]
Regarding No 1 - Would it be possible to add the time the report registered as well as the delay?

So, for example "Op 22:20 +10"

**Comment by LinqToException** [comment]
From a space point of view, I feel like it would get a bit bloaty, so I'd rather just have a delay label here for the time being. I could offer you the actual time as a tooltip without much effort.

In the far future, I'd like to offer additional configuration for the columns as-is. Having a badge or the label could be one of them.

One question that I have is still about the presentation today: Is it not necessary to differentiate between arrival and departure at a station? Is it really just about "I've seen this train doing something at that station which it did so-and-so late"?

**Comment by DazrahT** [comment]
"I've seen this train doing something at that station which it did so-and-so late"? - Pretty much, I'll not get into "Overdue reports" just yet as that'll just open a can of worms! 🤣

**Comment by LinqToException** [comment]
I suppose we'll start with a tooltip then and... figure out if that works for us.
![image](https://github.com/LinqToException/VirTracks/assets/47725963/7de67d02-baf1-41bc-8b9d-ae6e928e7fb3)

**Comment by DazrahT** [comment]
Oh you're good!

I only started using VirTracks over simrail.app EDR by the way for the colour scheme you've used (it's intutive, the green for "in the station" is a great help), but more I use it for the (current) ability to just hover over a train and see _where_ a train actually is and how late it was there, which helps more with decision making.  

If anything you were already halfway there with VirTracks in its current incarnation, I've just suggested my little input so it's more prominent on the table.

**Comment by LinqToException** [comment]
I've just pushed 2.3.0, which adds this column (along with two others). When you enable the guinea pig mode (🐹), you should be able to drag-and-drop the column into the used columns. I've not extensively tested it yet, but I feel like it's working okayish.

I'm closing the issue for now, but feel free to comment/open it again if something isn't right.

**Comment by DazrahT** [comment]
Perfect, thank you for pushing it out so quickly, I'll keep my eye on it and if I see something that's not quite right I'll comment back here as requested. Regards Daz.
